export type AssetClass = "Forex" | "Crypto" | "Stocks" | "Futures";
export type Side = "Long" | "Short";
export type TradeStatus = "closed" | "open";

export interface Trade {
  id: string;
  date: string; // ISO date string
  closeDate?: string;
  symbol: string;
  assetClass: AssetClass;
  side: Side;
  qty: number;
  avgFill: number;
  closePrice?: number;
  pnl?: number;
  pnlPct?: number;
  duration?: string; // e.g. "2h 14m"
  status: TradeStatus;
  notes?: string;
}

export interface Position {
  id: string;
  symbol: string;
  assetClass: AssetClass;
  side: Side;
  qty: number;
  avgCost: number;
  lastPrice: number;
  pnl: number;
  pnlPct: number;
}

export interface DailyPnl {
  date: string;
  pnl: number;
  cumulative: number;
}

// ── Helper ──────────────────────────────────────────────────────────────────

function fmt(n: number) {
  return parseFloat(n.toFixed(2));
}

function addDays(base: Date, days: number): string {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

// Base date: 90 days ago
const BASE = new Date("2026-02-23");

// ── Daily P&L (90 days) ─────────────────────────────────────────────────────

const RAW_DAILY: number[] = [
  120, -45, 310, -200, 88, 450, -130, 220, -60, 380,
  -95, 175, 530, -210, 90, -40, 260, 145, -180, 410,
  230, -75, 185, -320, 140, 560, -90, 200, 330, -115,
  155, -250, 480, 70, -160, 390, -85, 245, 190, -110,
  420, 160, -55, 280, -190, 350, 95, -230, 175, 440,
  -100, 210, 130, -285, 370, 115, -170, 500, -60, 220,
  300, -145, 185, 270, -95, 410, 65, -180, 340, 155,
  -220, 490, 80, -135, 260, 195, -70, 375, 130, -245,
  310, 170, -90, 425, 60, -155, 280, 210, -80, 360,
];

let cum = 0;
export const DAILY_PNL: DailyPnl[] = RAW_DAILY.map((pnl, i) => {
  cum += pnl;
  return { date: addDays(BASE, i), pnl: fmt(pnl), cumulative: fmt(cum) };
});

// ── Historical Trades (50+) ─────────────────────────────────────────────────

export const TRADES: Trade[] = [
  // --- Forex ---
  {
    id: "t1",
    date: addDays(BASE, 0),
    closeDate: addDays(BASE, 1),
    symbol: "EUR/USD",
    assetClass: "Forex",
    side: "Long",
    qty: 100000,
    avgFill: 1.0852,
    closePrice: 1.0864,
    pnl: 120,
    pnlPct: 0.11,
    duration: "18h 22m",
    status: "closed",
  },
  {
    id: "t2",
    date: addDays(BASE, 1),
    closeDate: addDays(BASE, 1),
    symbol: "GBP/USD",
    assetClass: "Forex",
    side: "Short",
    qty: 50000,
    avgFill: 1.2715,
    closePrice: 1.2724,
    pnl: -45,
    pnlPct: -0.07,
    duration: "4h 10m",
    status: "closed",
  },
  {
    id: "t3",
    date: addDays(BASE, 2),
    closeDate: addDays(BASE, 3),
    symbol: "USD/JPY",
    assetClass: "Forex",
    side: "Long",
    qty: 100000,
    avgFill: 149.85,
    closePrice: 150.16,
    pnl: 310,
    pnlPct: 0.21,
    duration: "1d 2h",
    status: "closed",
  },
  {
    id: "t4",
    date: addDays(BASE, 3),
    closeDate: addDays(BASE, 3),
    symbol: "EUR/GBP",
    assetClass: "Forex",
    side: "Short",
    qty: 75000,
    avgFill: 0.8542,
    closePrice: 0.8559,
    pnl: -200,
    pnlPct: -0.2,
    duration: "6h 5m",
    status: "closed",
  },
  {
    id: "t5",
    date: addDays(BASE, 4),
    closeDate: addDays(BASE, 4),
    symbol: "AUD/USD",
    assetClass: "Forex",
    side: "Long",
    qty: 50000,
    avgFill: 0.6492,
    closePrice: 0.651,
    pnl: 88,
    pnlPct: 0.28,
    duration: "3h 45m",
    status: "closed",
  },
  // --- Crypto ---
  {
    id: "t6",
    date: addDays(BASE, 5),
    closeDate: addDays(BASE, 6),
    symbol: "BTC/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 0.5,
    avgFill: 42350,
    closePrice: 43250,
    pnl: 450,
    pnlPct: 2.12,
    duration: "22h 14m",
    status: "closed",
  },
  {
    id: "t7",
    date: addDays(BASE, 6),
    closeDate: addDays(BASE, 6),
    symbol: "ETH/USD",
    assetClass: "Crypto",
    side: "Short",
    qty: 3,
    avgFill: 2285,
    closePrice: 2328,
    pnl: -130,
    pnlPct: -1.88,
    duration: "8h 30m",
    status: "closed",
  },
  {
    id: "t8",
    date: addDays(BASE, 7),
    closeDate: addDays(BASE, 8),
    symbol: "SOL/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 20,
    avgFill: 98.4,
    closePrice: 99.5,
    pnl: 220,
    pnlPct: 1.12,
    duration: "1d 4h",
    status: "closed",
  },
  {
    id: "t9",
    date: addDays(BASE, 9),
    closeDate: addDays(BASE, 9),
    symbol: "BTC/USD",
    assetClass: "Crypto",
    side: "Short",
    qty: 0.25,
    avgFill: 43800,
    closePrice: 44040,
    pnl: -60,
    pnlPct: -0.55,
    duration: "5h 20m",
    status: "closed",
  },
  {
    id: "t10",
    date: addDays(BASE, 10),
    closeDate: addDays(BASE, 11),
    symbol: "ETH/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 5,
    avgFill: 2210,
    closePrice: 2286,
    pnl: 380,
    pnlPct: 3.44,
    duration: "1d 6h",
    status: "closed",
  },
  // --- Stocks ---
  {
    id: "t11",
    date: addDays(BASE, 11),
    closeDate: addDays(BASE, 11),
    symbol: "AAPL",
    assetClass: "Stocks",
    side: "Long",
    qty: 50,
    avgFill: 188.42,
    closePrice: 190.3,
    pnl: 94,
    pnlPct: 1.0,
    duration: "6h 30m",
    status: "closed",
  },
  {
    id: "t12",
    date: addDays(BASE, 11),
    closeDate: addDays(BASE, 12),
    symbol: "NVDA",
    assetClass: "Stocks",
    side: "Long",
    qty: 10,
    avgFill: 495.8,
    closePrice: 499.0,
    pnl: -95,
    pnlPct: -0.65,
    duration: "1d 0h",
    status: "closed",
  },
  {
    id: "t13",
    date: addDays(BASE, 13),
    closeDate: addDays(BASE, 14),
    symbol: "TSLA",
    assetClass: "Stocks",
    side: "Short",
    qty: 30,
    avgFill: 248.5,
    closePrice: 241.9,
    pnl: 175,
    pnlPct: 2.66,
    duration: "1d 2h",
    status: "closed",
  },
  {
    id: "t14",
    date: addDays(BASE, 14),
    closeDate: addDays(BASE, 15),
    symbol: "MSFT",
    assetClass: "Stocks",
    side: "Long",
    qty: 20,
    avgFill: 412.3,
    closePrice: 438.8,
    pnl: 530,
    pnlPct: 6.43,
    duration: "1d 4h",
    status: "closed",
  },
  {
    id: "t15",
    date: addDays(BASE, 15),
    closeDate: addDays(BASE, 15),
    symbol: "AMZN",
    assetClass: "Stocks",
    side: "Long",
    qty: 40,
    avgFill: 178.6,
    closePrice: 175.4,
    pnl: -210,
    pnlPct: -1.79,
    duration: "5h 50m",
    status: "closed",
  },
  {
    id: "t16",
    date: addDays(BASE, 16),
    closeDate: addDays(BASE, 16),
    symbol: "META",
    assetClass: "Stocks",
    side: "Short",
    qty: 15,
    avgFill: 502.4,
    closePrice: 496.4,
    pnl: 90,
    pnlPct: 1.19,
    duration: "4h 15m",
    status: "closed",
  },
  {
    id: "t17",
    date: addDays(BASE, 17),
    closeDate: addDays(BASE, 17),
    symbol: "GOOGL",
    assetClass: "Stocks",
    side: "Long",
    qty: 25,
    avgFill: 175.2,
    closePrice: 173.6,
    pnl: -40,
    pnlPct: -0.91,
    duration: "3h 30m",
    status: "closed",
  },
  // --- Futures ---
  {
    id: "t18",
    date: addDays(BASE, 18),
    closeDate: addDays(BASE, 19),
    symbol: "ES",
    assetClass: "Futures",
    side: "Long",
    qty: 1,
    avgFill: 5125.5,
    closePrice: 5138.5,
    pnl: 260,
    pnlPct: 0.25,
    duration: "1d 1h",
    status: "closed",
  },
  {
    id: "t19",
    date: addDays(BASE, 19),
    closeDate: addDays(BASE, 19),
    symbol: "NQ",
    assetClass: "Futures",
    side: "Short",
    qty: 1,
    avgFill: 18240.0,
    closePrice: 18148.75,
    pnl: 145,
    pnlPct: 0.5,
    duration: "7h 45m",
    status: "closed",
  },
  {
    id: "t20",
    date: addDays(BASE, 20),
    closeDate: addDays(BASE, 20),
    symbol: "CL",
    assetClass: "Futures",
    side: "Long",
    qty: 2,
    avgFill: 78.42,
    closePrice: 77.52,
    pnl: -180,
    pnlPct: -1.15,
    duration: "6h 0m",
    status: "closed",
  },
  {
    id: "t21",
    date: addDays(BASE, 21),
    closeDate: addDays(BASE, 22),
    symbol: "GC",
    assetClass: "Futures",
    side: "Long",
    qty: 1,
    avgFill: 2028.4,
    closePrice: 2049.6,
    pnl: 410,
    pnlPct: 1.04,
    duration: "1d 5h",
    status: "closed",
  },
  // More trades to fill out 50+
  {
    id: "t22",
    date: addDays(BASE, 22),
    closeDate: addDays(BASE, 23),
    symbol: "EUR/USD",
    assetClass: "Forex",
    side: "Short",
    qty: 100000,
    avgFill: 1.0892,
    closePrice: 1.0869,
    pnl: 230,
    pnlPct: 0.21,
    duration: "1d 0h",
    status: "closed",
  },
  {
    id: "t23",
    date: addDays(BASE, 23),
    closeDate: addDays(BASE, 23),
    symbol: "XRP/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 5000,
    avgFill: 0.548,
    closePrice: 0.5335,
    pnl: -75,
    pnlPct: -2.74,
    duration: "9h 0m",
    status: "closed",
  },
  {
    id: "t24",
    date: addDays(BASE, 24),
    closeDate: addDays(BASE, 24),
    symbol: "SPY",
    assetClass: "Stocks",
    side: "Long",
    qty: 30,
    avgFill: 512.4,
    closePrice: 518.6,
    pnl: 185,
    pnlPct: 1.21,
    duration: "6h 30m",
    status: "closed",
  },
  {
    id: "t25",
    date: addDays(BASE, 25),
    closeDate: addDays(BASE, 25),
    symbol: "ES",
    assetClass: "Futures",
    side: "Short",
    qty: 2,
    avgFill: 5155.25,
    closePrice: 5187.5,
    pnl: -320,
    pnlPct: -0.63,
    duration: "4h 15m",
    status: "closed",
  },
  {
    id: "t26",
    date: addDays(BASE, 26),
    closeDate: addDays(BASE, 27),
    symbol: "BTC/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 0.75,
    avgFill: 43200,
    closePrice: 43948,
    pnl: 560,
    pnlPct: 1.73,
    duration: "1d 8h",
    status: "closed",
  },
  {
    id: "t27",
    date: addDays(BASE, 27),
    closeDate: addDays(BASE, 27),
    symbol: "GBP/JPY",
    assetClass: "Forex",
    side: "Long",
    qty: 50000,
    avgFill: 190.42,
    closePrice: 190.6,
    pnl: -90,
    pnlPct: -0.09,
    duration: "5h 30m",
    status: "closed",
  },
  {
    id: "t28",
    date: addDays(BASE, 28),
    closeDate: addDays(BASE, 29),
    symbol: "NVDA",
    assetClass: "Stocks",
    side: "Long",
    qty: 15,
    avgFill: 488.6,
    closePrice: 502.0,
    pnl: 200,
    pnlPct: 2.74,
    duration: "1d 3h",
    status: "closed",
  },
  {
    id: "t29",
    date: addDays(BASE, 29),
    closeDate: addDays(BASE, 30),
    symbol: "NQ",
    assetClass: "Futures",
    side: "Long",
    qty: 1,
    avgFill: 18085.5,
    closePrice: 18251.75,
    pnl: 330,
    pnlPct: 0.92,
    duration: "1d 2h",
    status: "closed",
  },
  {
    id: "t30",
    date: addDays(BASE, 30),
    closeDate: addDays(BASE, 30),
    symbol: "ETH/USD",
    assetClass: "Crypto",
    side: "Short",
    qty: 4,
    avgFill: 2352,
    closePrice: 2380.8,
    pnl: -115,
    pnlPct: -1.22,
    duration: "6h 45m",
    status: "closed",
  },
  {
    id: "t31",
    date: addDays(BASE, 31),
    closeDate: addDays(BASE, 31),
    symbol: "AAPL",
    assetClass: "Stocks",
    side: "Short",
    qty: 60,
    avgFill: 192.8,
    closePrice: 190.2,
    pnl: 155,
    pnlPct: 1.35,
    duration: "5h 0m",
    status: "closed",
  },
  {
    id: "t32",
    date: addDays(BASE, 32),
    closeDate: addDays(BASE, 33),
    symbol: "USD/CAD",
    assetClass: "Forex",
    side: "Long",
    qty: 100000,
    avgFill: 1.3542,
    closePrice: 1.3515,
    pnl: -250,
    pnlPct: -0.2,
    duration: "1d 0h",
    status: "closed",
  },
  {
    id: "t33",
    date: addDays(BASE, 33),
    closeDate: addDays(BASE, 34),
    symbol: "CL",
    assetClass: "Futures",
    side: "Short",
    qty: 2,
    avgFill: 80.14,
    closePrice: 75.76,
    pnl: 480,
    pnlPct: 5.46,
    duration: "1d 6h",
    status: "closed",
  },
  {
    id: "t34",
    date: addDays(BASE, 34),
    closeDate: addDays(BASE, 34),
    symbol: "SOL/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 30,
    avgFill: 102.4,
    closePrice: 104.7,
    pnl: 70,
    pnlPct: 2.25,
    duration: "7h 0m",
    status: "closed",
  },
  {
    id: "t35",
    date: addDays(BASE, 35),
    closeDate: addDays(BASE, 35),
    symbol: "META",
    assetClass: "Stocks",
    side: "Long",
    qty: 20,
    avgFill: 494.2,
    closePrice: 486.2,
    pnl: -160,
    pnlPct: -1.62,
    duration: "6h 15m",
    status: "closed",
  },
  {
    id: "t36",
    date: addDays(BASE, 36),
    closeDate: addDays(BASE, 37),
    symbol: "EUR/USD",
    assetClass: "Forex",
    side: "Long",
    qty: 150000,
    avgFill: 1.0814,
    closePrice: 1.084,
    pnl: 390,
    pnlPct: 0.24,
    duration: "1d 4h",
    status: "closed",
  },
  {
    id: "t37",
    date: addDays(BASE, 37),
    closeDate: addDays(BASE, 37),
    symbol: "GC",
    assetClass: "Futures",
    side: "Short",
    qty: 1,
    avgFill: 2062.8,
    closePrice: 2067.1,
    pnl: -85,
    pnlPct: -0.21,
    duration: "5h 45m",
    status: "closed",
  },
  {
    id: "t38",
    date: addDays(BASE, 38),
    closeDate: addDays(BASE, 39),
    symbol: "TSLA",
    assetClass: "Stocks",
    side: "Long",
    qty: 25,
    avgFill: 235.6,
    closePrice: 245.4,
    pnl: 245,
    pnlPct: 4.16,
    duration: "1d 2h",
    status: "closed",
  },
  {
    id: "t39",
    date: addDays(BASE, 39),
    closeDate: addDays(BASE, 39),
    symbol: "BTC/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 0.3,
    avgFill: 44200,
    closePrice: 44835,
    pnl: 190,
    pnlPct: 1.44,
    duration: "8h 30m",
    status: "closed",
  },
  {
    id: "t40",
    date: addDays(BASE, 40),
    closeDate: addDays(BASE, 40),
    symbol: "USD/JPY",
    assetClass: "Forex",
    side: "Short",
    qty: 100000,
    avgFill: 151.24,
    closePrice: 151.35,
    pnl: -110,
    pnlPct: -0.07,
    duration: "4h 0m",
    status: "closed",
  },
  {
    id: "t41",
    date: addDays(BASE, 41),
    closeDate: addDays(BASE, 42),
    symbol: "ES",
    assetClass: "Futures",
    side: "Long",
    qty: 2,
    avgFill: 5182.75,
    closePrice: 5224.75,
    pnl: 420,
    pnlPct: 0.81,
    duration: "1d 6h",
    status: "closed",
  },
  {
    id: "t42",
    date: addDays(BASE, 42),
    closeDate: addDays(BASE, 42),
    symbol: "AMZN",
    assetClass: "Stocks",
    side: "Short",
    qty: 35,
    avgFill: 182.4,
    closePrice: 177.8,
    pnl: 160,
    pnlPct: 2.52,
    duration: "5h 30m",
    status: "closed",
  },
  {
    id: "t43",
    date: addDays(BASE, 43),
    closeDate: addDays(BASE, 43),
    symbol: "AVAX/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 100,
    avgFill: 38.42,
    closePrice: 39.0,
    pnl: -55,
    pnlPct: -1.51,
    duration: "6h 0m",
    status: "closed",
  },
  {
    id: "t44",
    date: addDays(BASE, 44),
    closeDate: addDays(BASE, 45),
    symbol: "GBP/USD",
    assetClass: "Forex",
    side: "Long",
    qty: 75000,
    avgFill: 1.2648,
    closePrice: 1.2685,
    pnl: 280,
    pnlPct: 0.29,
    duration: "1d 3h",
    status: "closed",
  },
  {
    id: "t45",
    date: addDays(BASE, 45),
    closeDate: addDays(BASE, 46),
    symbol: "MSFT",
    assetClass: "Stocks",
    side: "Short",
    qty: 25,
    avgFill: 425.8,
    closePrice: 434.5,
    pnl: -190,
    pnlPct: -2.04,
    duration: "1d 1h",
    status: "closed",
  },
  {
    id: "t46",
    date: addDays(BASE, 46),
    closeDate: addDays(BASE, 47),
    symbol: "ETH/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 6,
    avgFill: 2268,
    closePrice: 2326,
    pnl: 350,
    pnlPct: 2.56,
    duration: "1d 5h",
    status: "closed",
  },
  {
    id: "t47",
    date: addDays(BASE, 47),
    closeDate: addDays(BASE, 47),
    symbol: "NQ",
    assetClass: "Futures",
    side: "Short",
    qty: 1,
    avgFill: 18345.25,
    closePrice: 18249.75,
    pnl: 95,
    pnlPct: 0.52,
    duration: "7h 15m",
    status: "closed",
  },
  {
    id: "t48",
    date: addDays(BASE, 48),
    closeDate: addDays(BASE, 48),
    symbol: "AUD/USD",
    assetClass: "Forex",
    side: "Short",
    qty: 100000,
    avgFill: 0.6584,
    closePrice: 0.6607,
    pnl: -230,
    pnlPct: -0.35,
    duration: "8h 45m",
    status: "closed",
  },
  {
    id: "t49",
    date: addDays(BASE, 49),
    closeDate: addDays(BASE, 50),
    symbol: "AAPL",
    assetClass: "Stocks",
    side: "Long",
    qty: 80,
    avgFill: 185.4,
    closePrice: 187.6,
    pnl: 175,
    pnlPct: 1.19,
    duration: "1d 4h",
    status: "closed",
  },
  {
    id: "t50",
    date: addDays(BASE, 50),
    closeDate: addDays(BASE, 51),
    symbol: "BTC/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 1.0,
    avgFill: 43550,
    closePrice: 43990,
    pnl: 440,
    pnlPct: 1.01,
    duration: "1d 6h",
    status: "closed",
  },
  {
    id: "t51",
    date: addDays(BASE, 51),
    closeDate: addDays(BASE, 51),
    symbol: "CL",
    assetClass: "Futures",
    side: "Long",
    qty: 1,
    avgFill: 76.28,
    closePrice: 75.28,
    pnl: -100,
    pnlPct: -1.31,
    duration: "5h 0m",
    status: "closed",
  },
  {
    id: "t52",
    date: addDays(BASE, 52),
    closeDate: addDays(BASE, 53),
    symbol: "NVDA",
    assetClass: "Stocks",
    side: "Long",
    qty: 12,
    avgFill: 510.4,
    closePrice: 527.95,
    pnl: 210,
    pnlPct: 3.44,
    duration: "1d 2h",
    status: "closed",
  },
  {
    id: "t53",
    date: addDays(BASE, 53),
    closeDate: addDays(BASE, 53),
    symbol: "SOL/USD",
    assetClass: "Crypto",
    side: "Short",
    qty: 40,
    avgFill: 107.8,
    closePrice: 104.55,
    pnl: 130,
    pnlPct: 3.01,
    duration: "9h 15m",
    status: "closed",
  },
  {
    id: "t54",
    date: addDays(BASE, 54),
    closeDate: addDays(BASE, 55),
    symbol: "EUR/USD",
    assetClass: "Forex",
    side: "Long",
    qty: 100000,
    avgFill: 1.0768,
    closePrice: 1.0740,
    pnl: -285,
    pnlPct: -0.26,
    duration: "1d 0h",
    status: "closed",
  },
  {
    id: "t55",
    date: addDays(BASE, 55),
    closeDate: addDays(BASE, 56),
    symbol: "ES",
    assetClass: "Futures",
    side: "Long",
    qty: 2,
    avgFill: 5204.5,
    closePrice: 5241.5,
    pnl: 370,
    pnlPct: 0.71,
    duration: "1d 4h",
    status: "closed",
  },
];

// ── Open Positions ──────────────────────────────────────────────────────────

export const POSITIONS: Position[] = [
  {
    id: "p1",
    symbol: "EUR/USD",
    assetClass: "Forex",
    side: "Long",
    qty: 100000,
    avgCost: 1.0842,
    lastPrice: 1.0867,
    pnl: 250,
    pnlPct: 0.23,
  },
  {
    id: "p2",
    symbol: "BTC/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 0.5,
    avgCost: 43800,
    lastPrice: 44950,
    pnl: 575,
    pnlPct: 2.62,
  },
  {
    id: "p3",
    symbol: "AAPL",
    assetClass: "Stocks",
    side: "Long",
    qty: 100,
    avgCost: 186.42,
    lastPrice: 188.75,
    pnl: 233,
    pnlPct: 1.25,
  },
  {
    id: "p4",
    symbol: "ES",
    assetClass: "Futures",
    side: "Short",
    qty: 1,
    avgCost: 5248.5,
    lastPrice: 5265.25,
    pnl: -337.5,
    pnlPct: -0.32,
  },
  {
    id: "p5",
    symbol: "ETH/USD",
    assetClass: "Crypto",
    side: "Long",
    qty: 3,
    avgCost: 2320,
    lastPrice: 2298,
    pnl: -66,
    pnlPct: -0.95,
  },
  {
    id: "p6",
    symbol: "NVDA",
    assetClass: "Stocks",
    side: "Long",
    qty: 20,
    avgCost: 498.6,
    lastPrice: 514.4,
    pnl: 316,
    pnlPct: 3.17,
  },
  {
    id: "p7",
    symbol: "GBP/USD",
    assetClass: "Forex",
    side: "Short",
    qty: 50000,
    avgCost: 1.274,
    lastPrice: 1.2758,
    pnl: -90,
    pnlPct: -0.14,
  },
];

// ── KPI summary numbers ─────────────────────────────────────────────────────

export const ACCOUNT = {
  netLiquidation: 125430.5,
  dailyPnl: 1234.5,
  dailyPnlPct: 0.99,
  openPnl: POSITIONS.reduce((s, p) => s + p.pnl, 0),
  openPnlPct: -0.27,
  winRate: 64.3,
};
